### ISSUE TITLE
Can't build on Ubuntu 19.10

### ISSUE THREAD

**Issue by dmt0** [manuel-rhdt/snd-microbookii#6]
Getting the following output:

```
buntu@ubuntu:~/snd-microbookii$ make
make -C /lib/modules/5.3.0-18-generic/build M=/home/ubuntu/snd-microbookii modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-18-generic'
  CC [M]  /home/ubuntu/snd-microbookii/audio.o
/home/ubuntu/snd-microbookii/audio.c:898:10: error: ‘snd_pcm_lib_mmap_vmalloc’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_mmap_iomem’?
  898 |  .mmap = snd_pcm_lib_mmap_vmalloc,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
      |          snd_pcm_lib_mmap_iomem
make[2]: *** [scripts/Makefile.build:290: /home/ubuntu/snd-microbookii/audio.o] Error 1
make[1]: *** [Makefile:1653: _module_/home/ubuntu/snd-microbookii] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-18-generic'
make: *** [Makefile:5: all] Error 2
```

If I make the suggested change, it builds with warnings.
Was able to `insmod` it, but couldn't test it as it doesn't want to show up in `lsusb`. Works fine on Windows though.

**Comment by Benitoite** [comment]
on Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

Successful `make` with same suggested change and successful `dkms` kernel integration.

```
$ lsusb
Bus 002 Device 003: ID 07fd:0004 Mark of the Unicorn 
```
but when recording a 16bit/44.1kHz track from the `MicrobookII: - (hw:2,0)` device in Audacity I get this error popup "Error opening sound device. Try changing the audio host, recording device and the project sample rate."
with console output:
```
Expression 'hostFormat = PaUtil_SelectClosestAvailableFormat( availableFormats, parameters->sampleFormat )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1786
```

Also, MicrobookII must be plugged in *after* boot.

**Comment by manuel-rhdt** [comment]
Please note that since linux kernel 5.1 the Microbook II is supported without the external kernel module. The patch may thus not be in current distribution kernel yet.

Also note that recording 44.1kHz track does not work with this driver. The driver is currently hard-coded to 96kHz.
